apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-admin
  namespace: cicd
  labels:
    app: jenkins-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-admin
  template:
    metadata:
      labels:
        app: jenkins-admin
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      volumes:
        - name: jenkins-home
          hostPath:
            path: /home/lyb01433051/lyb/jenkins
            type: DirectoryOrCreate
      containers:
        - image: jenkins/jenkins:2.387.1
          imagePullPolicy: IfNotPresent
          name: jenkins-admin
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
            - containerPort: 50000
              name: agent
              protocol: TCP
          volumeMounts:
            - mountPath: /var/jenkins_home/
              name: jenkins-home
          env:
            - name: JAVA_OPTS
              value: -Duser.timezone=Asia/Shanghai
          securityContext:
            privileged: true
            runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-admin
  namespace: cicd
spec:
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30108
    - name: agent
      port: 50000
      targetPort: 50000
      protocol: TCP
      nodePort: 30109
  selector:
    app: jenkins-admin